name: Automated Release Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 20
  IP_ADDRESS: 'theakar.link'

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Application
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: |
          bun install
          bun build:live
          tar -czf ${{ github.sha }}.tar.gz .output
      - name: Store app-artifacts for distribution
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: ${{ github.sha }}.tar.gz
      - uses: actions/download-artifact@v3
        with:
          name: app-artifacts
      - name: Upload app-artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.IP_ADDRESS }}
          port: '222'
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ github.sha }}.tar.gz
          target: ~/server/artifacts
      - name: Activate Release
        uses: appleboy/ssh-action@master
        env:
          RELEASE_PATH: ~/server/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ~/server/live
        with:
          host: ${{ env.IP_ADDRESS }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p "~/server/releases/${GITHUB_SHA}"
            tar xzf ~/server/artifacts/${GITHUB_SHA}.tar.gz -C "~/server/releases/${GITHUB_SHA}"
            tar xzf ~/server/artifacts/${GITHUB_SHA}-database.tar.gz -C "~/server"
            rm -rf ~/server/artifacts/${GITHUB_SHA}.tar.gz
            ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
            systemctl restart yck.nuxtblog.service
            cd ~/server/releases && ls -t -1 | tail -n +4 | xargs rm -rf
            cd ~/server/artifacts && rm -rf *
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: app-artifacts
