name: Automated Release Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 20
  IP_ADDRESS: 'theakar.link'

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Application
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
          run: bun install
          
  
